version: "3"
services:
  web:
    build: ./Frontend
    ports:
      - "8080:8080"
    depends_on:
      - api
  api:
    build: ./Backend
    ports:
      - "8082:8082"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"