export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const RETRIEVE_DEPARTMENTS = "RETRIEVE_DEPARTMENTS";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";

export const IS_LOADING = 'IS_LOADING';

export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const RETRIEVE_EMPLOYEES = "RETRIEVE_EMPLOYEES";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";

export const CHANGE_EDITING_REGISTER = 'CHANGE_EDITING_REGISTER';

export const API_ERROR = 'API_ERROR';